### ISSUE TITLE
Can i get more information about this project

### ISSUE THREAD

**Issue by tory1103** [democritus-project/d8s-python#34]
I want to colaborate on this project, but i dont really understand it.
There are no documentation about it, you should think about creating one...
Also, d8s-python file functions are so messy....
I hope to receive a reply soon.

**Comment by fhightower** [comment]
Hi @tory1103, thanks for reaching out!

**To your question about what this project is:** The democritus project started as a dream to create cleaner, simpler interfaces for doing things in Python. I started this project to meet some needs I had in some other projects. The idea is to write simple, modular, well-tested, and composable functions making it easier to craft readable, effective, and maintainable software. This project is not my primary focus right now, but I'm happy to merge PRs.

**To your question about documentation:** I actually have a novel documentation system for this project, but it needs some work and I haven't released it yet. For now, the documentation lives in the project's [readme](https://github.com/democritus-project/d8s-python#functions).

**To your comment about messy functions:** Two thoughts here:
   1.  What makes you say the code is messy?
   2. I'm happy to merge PRs if you want to help clean it up!

**Comment by tory1103** [comment]
Glad to write you back.
I have just commited a pull request, consider to merge it.
Thanks
