### ISSUE TITLE
Write function to find number of lines in python code

### ISSUE THREAD

**Issue by fhightower** [democritus-project/d8s-python#7]
HELP WANTED 👋  : If you'd like to take this challenge on, please let me know! Even if you're new to Python and/or Github, this is a great place to start and I'd be happy to help walk you through this challenge as much as you need - don't hesitate to ask.

This particular issue will give you some exposure to writing a simple function and writing tests for that function.

---

# What?

I would like a function to find the number of lines in Python code.

I envision the signature of such a function looking like:

```
def python_line_count(python_code: str, *, ignore_empty_lines: bool = True) -> int:
```

# Why?

Counting lines of code is a common use-case.

# How?

This function can be modeled on the [python_function_line_count](https://github.com/democritus-project/democritus-python/blob/4f1a3db79002ea1ed660d5bdae894c2bad7743e4/democritus_python/python_data.py#L123) function.

**Comment by ShrutiKatpara** [comment]
Hey, I would like to take this up. I am a complete newbie on making contributions on github. And so I would need some help to accomplish the challenge. I hope you don't mind that. 

Can you please tell that in which files I have to make changes. Is it the [modeled function](https://github.com/democritus-project/democritus-python/blob/4f1a3db79002ea1ed660d5bdae894c2bad7743e4/democritus_python/python_data.py#L123) ?

**Comment by fhightower** [comment]
Wonderful 🎉  ! Thanks for wanting to be involved and I don't mind helping at all @ShrutiKatpara!

Here is the process we'll follow:

0. Claim the task/issue you want to work on
    - This is already done! I've assigned this issue to you and we'll close it when you're done.
1. [Fork][fork] this repository
2. [Clone][clone] the forked repository locally
3. [Create a branch][branch]
    - I recommend starting your branch name with the issue number you are working on (in this case, issue #7) 
    - I also recommend giving your branch a helpful name
    - Combining these ^ two points of advice, I'd suggest naming your branch something like `7-add-line-count-func`
4. Make your code changes
    - This is where you actually modify and improve the code
5. Write tests
    - All new functions should have some tests written for them
6. Push your changes to your fork
7. [Create a pull request][pr] from your fork to this repository
8. We'll review the updates you made and merge the PR!

## Questions? Please Ask!

If you have any follow-up questions, don't hesitate to ask! It takes practice to understand how to contribute to software, so there is no shame in asking for help.

[fork]: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
[clone]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository
[branch]: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
[pr]: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ShrutiKatpara** [comment]
Hey @fhightower. Just to be clear. I saw that the [python_function_line_count](https://github.com/democritus-project/d8s-python/blob/4f1a3db79002ea1ed660d5bdae894c2bad7743e4/democritus_python/python_data.py#L123) is already implemented in the package. 

Is my task to test the function by generating test files and correct the function wherever it fails?

**Comment by fhightower** [comment]
Thanks for asking @ShrutiKatpara and I have to apologize; my original comment was not very clear and was misleading.

I think the best approach is to rename the [python_function_line_count](https://github.com/democritus-project/d8s-python/blob/4f1a3db79002ea1ed660d5bdae894c2bad7743e4/democritus_python/python_data.py#L123) to make it more general. Currently, the name of the function makes it sound like it only counts lines for functions, but this is not the case; it can count lines for any given string of code. So, your task is to update the name of the function `python_function_line_count` to `python_line_count` (or something like that) and then update:

- any arguments to the function to make them more general
- all references to `python_function_line_count` throughout this file and the tests

Does that make sense? Thanks again for clarifying this.

**Comment by ShrutiKatpara** [comment]
Yeah sure. Thanks @fhightower . I think I misunderstood the task. Thanks for clarifying me.

**Comment by riyalalwani19** [comment]
I would also like to work on this. Is it possible to assign it to two people?

**Comment by fhightower** [comment]
Thanks for reaching out @riyalalwani19 👋  !

Yes, we can assign two people to this issue, but that is up to @ShrutiKatpara . @ShrutiKatpara: would you like some help from @riyalalwani19 on this issue or do you prefer to work on it alone? Either way is fine.

In the mean time, @riyalalwani19, there are some other issues in the Democritus Project for which we are looking for help:

- https://github.com/democritus-project/d8s-dates/issues/10
- https://github.com/democritus-project/d8s-networking/issues/3

Please let me know if any one of these (or any other issue) looks interesting.

**Comment by ShrutiKatpara** [comment]
I have no issues to collaborate with @riyalalwani19 . I would be happy instead. Thanks.

**Comment by fhightower** [comment]
Sweet, I've added @riyalalwani19 as an assignee for this issue.

Also, I've merged a PR that updated this repo so you may want to pull the changes if you have this repo cloned locally.
